### ISSUE TITLE
Exception: Royalty Patch

### ISSUE THREAD

**Issue by Fumblesneeze** [Zylleon/Gemstones#2]
```
[Gemstones] Patch operation Verse.PatchOperationFindMod(Royalty) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2000801414\1.1\Patches\Patches.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
```

Well I *do* have Royalty installed and active...

**Comment by Zylleon** [comment]
I can't get that error to show up. I tried with and without Royalty active, and with Royalty and Gemstones in either order. Do you have any other mods that might affect it?

**Comment by Fumblesneeze** [comment]
Hm I have a bunch of mods, don't think anything would interfere with this here though.

Here's my modlist:

  0. [Harmony](https://github.com/pardeike/HarmonyRimWorld)
  1. RimWorld
  2. Royalty
  3. [HugsLib](https://ludeon.com/forums/index.php?topic=28066.0)
  4. [HD Terrain Texture Pack](http://steamcommunity.com/sharedfiles/filedetails/?id=1292715618)
  5. [[1.1] MegaCorp](http://steamcommunity.com/sharedfiles/filedetails/?id=2017276648)
  6. [GroundClear](http://steamcommunity.com/sharedfiles/filedetails/?id=2013560306)
  7. [[WD] Hands Are Not Outside](http://steamcommunity.com/sharedfiles/filedetails/?id=1985331019)
  8. [Sand Castles](http://steamcommunity.com/sharedfiles/filedetails/?id=1980394843)
  9. [Go Explore!](https://ludeon.com/forums/index.php?topic=49239.0)
 10. [Yayo's Meteor](http://steamcommunity.com/sharedfiles/filedetails/?id=1979642019)
 11. [Space Western (Music Pack)](http://steamcommunity.com/sharedfiles/filedetails/?id=1953447132)
 12. [Solar Flares Affect Mechanoids](http://steamcommunity.com/sharedfiles/filedetails/?id=1906174567)
 13. [Terrain Zone Selections](https://github.com/MSeal/RimworldTerrainZoneSelect)
 14. [Let's Trade!](https://github.com/earthyturtle/LetsTrade)
 15. [Vanilla Events Expanded](http://steamcommunity.com/sharedfiles/filedetails/?id=1938420742)
 16. [Vanilla Fishing Expanded](http://steamcommunity.com/sharedfiles/filedetails/?id=1914064942)
 17. [Thrumbo Horn Melee Weapons](http://steamcommunity.com/sharedfiles/filedetails/?id=1935048195)
 18. [Architect Icons](http://steamcommunity.com/sharedfiles/filedetails/?id=1195427067)
 19. [Wall Vitals Monitor](http://steamcommunity.com/sharedfiles/filedetails/?id=1334289344)
 20. [More Linkables](http://steamcommunity.com/sharedfiles/filedetails/?id=1103809207)
 21. [[KV] RimFridge - 1.1](https://ludeon.com/forums/index.php?topic=32980.0)
 22. [Where is my weapon?](http://steamcommunity.com/sharedfiles/filedetails/?id=1539028008)
 23. [Avoid Friendly Fire](http://steamcommunity.com/sharedfiles/filedetails/?id=1134165362)
 24. [Interaction Bubbles](http://steamcommunity.com/sharedfiles/filedetails/?id=1516158345)
 25. [Extra Alerts](http://steamcommunity.com/sharedfiles/filedetails/?id=1926923167)
 26. [[WD] Fueled Heaters](http://steamcommunity.com/sharedfiles/filedetails/?id=1924942266)
 27. [Massivity](http://steamcommunity.com/sharedfiles/filedetails/?id=1908867964)
 28. [Armor Racks](http://steamcommunity.com/sharedfiles/filedetails/?id=1875828205)
 29. [Matching Embrasures](http://steamcommunity.com/sharedfiles/filedetails/?id=937587020)
 30. [Dubs Rimkit](http://steamcommunity.com/sharedfiles/filedetails/?id=832333531)
 31. [[WD] Realistic Darkness](http://steamcommunity.com/sharedfiles/filedetails/?id=1531882210)
 32. [[SYR] Terrain](http://steamcommunity.com/sharedfiles/filedetails/?id=1544439671)
 33. [RPG Style Inventory](http://steamcommunity.com/sharedfiles/filedetails/?id=1561221991)
 34. [Mining Priority](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
 35. [4M Mehni's Misc Modifications](https://github.com/Mehni/4M-Mehni-s-Misc-Modifications/releases/latest)
 36. [[KV] Force Do Job - 1.1](http://steamcommunity.com/sharedfiles/filedetails/?id=937170538)
 37. [Cut plants before building](http://steamcommunity.com/sharedfiles/filedetails/?id=1539025677)
 38. [RePowerReborn](https://github.com/EbonJaeger/RePowerReborn)
 39. [Caravan Auto-Bedroll](http://steamcommunity.com/sharedfiles/filedetails/?id=1690712826)
 40. [Micro Designations](none)
 41. [Gear Up And Go](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
 42. [Better Pawn Control](http://steamcommunity.com/sharedfiles/filedetails/?id=1541460369)
 43. [Metals Trader](http://steamcommunity.com/sharedfiles/filedetails/?id=1855069167)
 44. [Map Wide Orbital Trade Beacon](https://steamcommunity.com/sharedfiles/filedetails/?id=1839069104)
 45. [More Filters](http://steamcommunity.com/sharedfiles/filedetails/?id=1911734422)
 46. [Do Something for Idle](http://steamcommunity.com/sharedfiles/filedetails/?id=1896806569)
 47. [Grazing Lands](none)
 48. [Mortar Accuracy](http://steamcommunity.com/sharedfiles/filedetails/?id=1729446857)
 49. [Quick Stockpile Creation](http://steamcommunity.com/sharedfiles/filedetails/?id=1742151109)
 50. [[KV] Trading Spot - 1.1](https://ludeon.com/forums/index.php?topic=33669.msg343859#msg343859)
 51. [Vanilla Armour Expanded](http://steamcommunity.com/sharedfiles/filedetails/?id=1814988282)
 52. [GloomyFurniture](http://steamcommunity.com/sharedfiles/filedetails/?id=1558635181)
 53. [P-Music](https://steamcommunity.com/sharedfiles/filedetails/?id=725130005)
 54. [Vanilla Weapons Expanded](http://steamcommunity.com/sharedfiles/filedetails/?id=1814383360)
 55. [Dubs Skylights](https://github.com/Dubwise56/Skylights)
 56. [RBSE Hardcore Edition](https://ludeon.com/forums/index.php?topic=28731.0)
 57. [Snap Out!](https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555)
 58. [[SYR] Prosthetic Icons](https://ludeon.com/forums/index.php?topic=42913.0)
 59. [[SYR] Scar Removal](https://ludeon.com/forums/index.php?topic=43449)
 60. [[SYR] Doormats](https://ludeon.com/forums/index.php?topic=43449)
 61. [[SYR] Marbled Marble](https://ludeon.com/forums/index.php?topic=43449)
 62. [[SYR] Set Up Camp](https://ludeon.com/forums/index.php?topic=43449.0)
 63. [Feed The Colonists](https://twitter.com/postrobcore)
 64. [Giddy-up! Core](http://steamcommunity.com/sharedfiles/filedetails/?id=1216999901)
 65. [Giddy-up! Battle Mounts](http://steamcommunity.com/sharedfiles/filedetails/?id=1217001091)
 66. [Giddy-up! Ride and Roll](http://steamcommunity.com/sharedfiles/filedetails/?id=1331961995)
 67. [Giddy-up! Caravan](http://steamcommunity.com/sharedfiles/filedetails/?id=1253251478)
 68. [Colony Manager](https://ludeon.com/forums/index.php?topic=16120.0)
 69. [LinkableDoors (unofficial)](https://github.com/Linkolas/rim-LinkableDoors)
 70. [[RF] Editable Backstories and Names - 1.1](https://ludeon.com/forums/index.php?topic=46165)
 71. [Room Food](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
 72. [Uninstall Rimworld (No Structures)](http://steamcommunity.com/sharedfiles/filedetails/?id=2018904829)
 73. [Cleaning Priority (Continued)](https://github.com/emipa606/CleaningPriority)
 74. [Ceiling Light](http://steamcommunity.com/sharedfiles/filedetails/?id=2017041639)
 75. [Drugs In Bulk](http://steamcommunity.com/sharedfiles/filedetails/?id=2016906815)
 76. [Fluffy Breakdowns](https://ludeon.com/forums/index.php?topic=16120.0)
 77. [Dubs Bad Hygiene](https://github.com/Dubwise56/Dubs-Bad-Hygiene/wiki)
 78. [Survival Tools Reborn](https://ludeon.com/forums/index.php?topic=29503.0)
 79. [Jewelry](http://steamcommunity.com/sharedfiles/filedetails/?id=2020964421)
 80. [Communicable Diseases [1.1]](http://steamcommunity.com/sharedfiles/filedetails/?id=2016577520)
 81. [Yayo's Shooting 2](http://steamcommunity.com/sharedfiles/filedetails/?id=2020785943)
 82. [Suppression](http://steamcommunity.com/sharedfiles/filedetails/?id=2016866580)
 83. [Enemy Self Preservation](http://steamcommunity.com/sharedfiles/filedetails/?id=2006638530)
 84. [Faction Resources](http://steamcommunity.com/sharedfiles/filedetails/?id=2006644524)
 85. [Tech Advancing](https://ludeon.com/forums/index.php?topic=22598.0)
 86. [Rimworld Search Agency](http://steamcommunity.com/sharedfiles/filedetails/?id=726479594)
 87. [Stack XXL](http://steamcommunity.com/sharedfiles/filedetails/?id=826366050)
 88. [Safely Hidden Away](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
 89. [[KV] More Trait Slots - 1.1](https://ludeon.com/forums/index.php?topic=45488.msg432745)
 90. [Meals On Wheels](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
 91. [Pharmacist](https://ludeon.com/forums/index.php?topic=16120)
 92. [Reverse Commands](http://steamcommunity.com/sharedfiles/filedetails/?id=858744731)
 93. [Map Reroll](https://ludeon.com/forums/index.php?topic=18073.0)
 94. [Relations Tab](https://ludeon.com/forums/index.php?topic=15964.0)
 95. [Medical Tab](http://steamcommunity.com/sharedfiles/filedetails/?id=715565817)
 96. [Work Tab](https://ludeon.com/forums/index.php?topic=15964.0)
 97. [Blueprints](https://ludeon.com/forums/index.php?topic=16120.0)
 98. [Animal Tab](https://ludeon.com/forums/index.php?topic=16120.0)
 99. [Heated Floors](http://steamcommunity.com/sharedfiles/filedetails/?id=1909573090)
100. [QualityBuilder](ludeon.com/forums/index.php?topic=25188.0)
101. [Pick Up And Haul](https://ludeon.com/forums/index.php?topic=35832)
102. [Realistic Rooms](https://discord.gg/YhWA6uZ)
103. [Dubs Break Mod](https://github.com/Dubwise56/Dubs-Break-Mod)
104. [Realistic Starvation](https://ludeon.com/forums/index.php?topic=31548.0)
105. [Outfitted](http://steamcommunity.com/sharedfiles/filedetails/?id=1595812861)
106. [Dynamic Diplomacy](http://steamcommunity.com/sharedfiles/filedetails/?id=1875168898)
107. [Auto-Cut Blight](http://steamcommunity.com/sharedfiles/filedetails/?id=1885186534)
108. [[KV] Show Hair With Hats or Hide All Hats - 1.1](https://ludeon.com/forums/index.php?topic=33575.msg342365#msg342365)
109. [NamesGalore](http://steamcommunity.com/sharedfiles/filedetails/?id=2017130910)
110. [Real Ruins](https://steamcommunity.com/id/telewre/myworkshopfiles/?appid=294100)
111. [Extended Turrets](https://ludeon.com/forums/index.php?topic=6770.0)
112. [Simple sidearms](https://steamcommunity.com/sharedfiles/filedetails/?id=927155256)
113. [Greyer morals (Continued)](https://github.com/emipa606/GreyerMorals)
114. [Traders Have Money](http://steamcommunity.com/sharedfiles/filedetails/?id=2022959333)
115. [Glass-Drum Bullpup Rifle](http://steamcommunity.com/sharedfiles/filedetails/?id=1967130419)
116. [Won hair_women ](http://steamcommunity.com/sharedfiles/filedetails/?id=1886150617)
117. [Gloomy Face mk2](https://steamcommunity.com/sharedfiles/filedetails/?id=1870677788)
118. [Share The Load](https://steamcommunity.com/id/Uuugggg/myworkshopfiles/?appid=294100)
119. [Allow Tool](https://ludeon.com/forums/index.php?topic=17218.0)
120. [Better Spots](http://steamcommunity.com/sharedfiles/filedetails/?id=1756297158)
121. [Invisible Conduit](http://steamcommunity.com/sharedfiles/filedetails/?id=2013416365)
122. [More vanilla factions](http://steamcommunity.com/sharedfiles/filedetails/?id=830221184)
123. [[KV] Faction Control - 1.1](https://ludeon.com/forums/index.php?board=15.0)
124. [Stabilize](https://github.com/Linkolas/RW_Stabilize)
125. [[CP] Detailed Body Textures II](http://steamcommunity.com/sharedfiles/filedetails/?id=1501435493)
126. [Veinminer R1.1](http://steamcommunity.com/sharedfiles/filedetails/?id=1541978411)
127. [[KV] Path Avoid - 1.1](https://ludeon.com/forums/index.php?topic=33027)
128. [Less Stupid Romance Attempt (Continued)](https://github.com/emipa606/LessStupidRomanceAttempt)
129. [Ammunition[1.1]](http://steamcommunity.com/sharedfiles/filedetails/?id=1892397131)
130. [Yayo's Combat 3](http://steamcommunity.com/sharedfiles/filedetails/?id=2038409475)
131. [More Shelves](http://steamcommunity.com/sharedfiles/filedetails/?id=1659929907)
132. [[1.1] Better Speed](https://github.com/Fumblesneeze/RimBetterSpeed)
133. [Plasma Weaponry](https://steamcommunity.com/id/Babo/myworkshopfiles/?appid=294100)
134. [Carry Capacity Fixed](https://github.com/DrZhivago1/Carry_Capacity_Fixed)
135. [Verify Start](http://steamcommunity.com/sharedfiles/filedetails/?id=1516689035)
136. [Crash Landing](https://ludeon.com/forums/index.php?topic=8967.465)
137. [Tables+](http://steamcommunity.com/sharedfiles/filedetails/?id=963265186)
138. [[1.1] Ice](https://github.com/Fumblesneeze/RimIce)
139. [Gemstones](http://steamcommunity.com/sharedfiles/filedetails/?id=2000801414)
140. [JecsTools](https://discord.gg/AaVFA7V)
141. [Save Our Ship 2](http://steamcommunity.com/sharedfiles/filedetails/?id=1909914131)
142. [More Psycasts (Reupload)](https://github.com/Metalocif/MorePsycasts)
143. [Retextured Apparel](http://steamcommunity.com/sharedfiles/filedetails/?id=2042613316)
144. [More Consumables and Mutagens (Continued)](https://github.com/emipa606/MoreConsumablesAndMutagens)
